# Generated by Django 3.2.8 on 2021-11-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('craeted_date', models.DateTimeField(auto_now_add=True)),
                ('active_status', models.BooleanField(null=True)),
            ],
        ),
    ]
