# Generated by Django 3.2.8 on 2021-11-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer_data', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customer Data'},
        ),
    ]
