# Generated by Django 3.2.8 on 2021-10-31 19:45

import Vendor_Company.media_path_converter
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor_Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='running_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_photo',
            field=models.ImageField(null=True, upload_to=Vendor_Company.media_path_converter.upload_image_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
