# Generated by Django 3.2.8 on 2021-10-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendor_Company', '0002_auto_20211101_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
