# Generated by Django 3.2.8 on 2021-11-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor_Company', '0003_alter_vendor_phone_number'),
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Transaction Method',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendor_Company.vendor')),
            ],
            options={
                'verbose_name_plural': 'Purchase Data',
            },
        ),
    ]
