# Generated by Django 3.2.8 on 2021-11-12 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendor_Company', '0001_initial'),
        ('Products', '0001_initial'),
        ('Customer_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction_Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Transaction Method',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(default=0, editable=False)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer_data.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('transaction_method', models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction_app.transaction_method')),
            ],
            options={
                'verbose_name_plural': 'Sale Data',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('total_amount', models.FloatField(default=0, editable=False)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('transaction_method', models.ForeignKey(default='None', null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction_app.transaction_method')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendor_Company.vendor')),
            ],
            options={
                'verbose_name_plural': 'Purchase Data',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_quantity', models.FloatField(default=0, null=True)),
                ('sale_quantity', models.FloatField(default=0, null=True)),
                ('total_quantity_balance', models.FloatField(default=0)),
                ('updated_date', models.DateTimeField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.product')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction_app.purchase')),
                ('sale', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction_app.sale')),
            ],
        ),
    ]
