# Generated by Django 3.2.8 on 2021-11-11 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_app', '0002_auto_20211111_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name_plural': 'Purchase Data'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name_plural': 'Sale Data'},
        ),
    ]
