# Generated by Django 3.2.8 on 2021-11-11 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_app', '0007_auto_20211111_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='purchase',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction_app.purchase'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_quantity',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='Transaction_app.sale'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_quantity',
            field=models.FloatField(default=0, null=True),
        ),
    ]
