# Generated by Django 3.2.8 on 2021-11-11 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_app', '0008_auto_20211111_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
