# Generated by Django 3.2.8 on 2021-11-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction_app', '0009_inventory_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
