# Generated by Django 3.2.8 on 2021-11-12 17:33

from django.db import migrations, models
import django.db.models.deletion
import employee_data.media_path_converter
import utilities.pdf_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_names', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('employee_profile_photo', models.ImageField(null=True, upload_to=employee_data.media_path_converter.upload_image_path)),
                ('employee_special_document_photo', models.ImageField(null=True, upload_to=employee_data.media_path_converter.em_document_path)),
                ('employee_cv', models.FileField(null=True, upload_to='Employee_CV/%Y/%m/%d', validators=[utilities.pdf_validator.pdf_validator])),
                ('district', models.CharField(max_length=50, null=True)),
                ('thana', models.CharField(max_length=50, null=True)),
                ('division', models.CharField(max_length=50, null=True)),
                ('post_office', models.CharField(max_length=50, null=True)),
                ('blood_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_data.blood_group')),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_data.employee_designation')),
            ],
        ),
    ]
