# Generated by Django 3.2.8 on 2021-11-09 16:00

from django.db import migrations, models
import employee_data.media_path_converter


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('em_profile_photo', models.ImageField(upload_to=employee_data.media_path_converter.upload_image_path)),
                ('special_document_photo', models.ImageField(upload_to=employee_data.media_path_converter.em_document_path)),
                ('blood_group', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('thana', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=50)),
            ],
        ),
    ]
