# Generated by Django 3.2.8 on 2021-11-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_data', '0002_auto_20211109_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='blood_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_data.blood_group'),
        ),
    ]
